"""add operational fields to cv_generation

Revision ID: 11b9e95751a5
Revises: a59996b23180
Create Date: 2026-10-06 17:23:45.902262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b9e95751a5'
down_revision: Union[str, Sequence[str], None] = 'a59996b23180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_generation', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cv_generation', sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cv_generation', sa.Column('total_input_tokens', sa.Integer(), nullable=False))
    op.add_column('cv_generation', sa.Column('total_output_tokens', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cv_generation_status'), 'cv_generation', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_generation_status'), table_name='cv_generation')
    op.drop_column('cv_generation', 'total_output_tokens')
    op.drop_column('cv_generation', 'total_input_tokens')
    op.drop_column('cv_generation', 'error')
    op.drop_column('cv_generation', 'status')
    # ### end Alembic commands ###
