MODEL = "openai/gpt-oss-20b"
BASE_URL = "https://api.groq.com/openai/v1"
PARSER_MODEL='inclusionai/ling-3.0-flash-vl:free'
EXPERIENCE_MODEL='openai/gpt-oss-20b'
SKILLS_MODEL='openai/gpt-oss-20b'
PROJECT_MODEL='openai/gpt-oss-20b'
SUMMARY_MODEL='openai/gpt-oss-20b'
EDUCATION_MODEL='openai/gpt-oss-20b'
MAX_EXPERIENCES=3
MAX_SKILLS_PER_CATEGORY = 6