from pydantic import field_validator, AnyUrl
from datetime import datetime
from uuid import UUID, uuid4
from typing import Optional, List
from sqlmodel import SQLModel, Field, Column, JSON

class Job(SQLModel, table = True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)

    source: str = Field(
        description="Where this job came from (firecrawl, greenhouse, lever, linkedin, etc.)"
    )
    url: str = Field(unique=True, index=True)
    company_id: Optional[UUID] = Field(default=None, foreign_key="company.id")
    company: str 
    title: str
    location: Optional[str] = None
    country: Optional[str] = None
    is_remote: bool = False
    remote_restrictions: Optional[str] = Field(
        default=None, description="Remote only in US, Europe, etc."
    )
    employment_type: Optional[str] = Field(
        default=None, description="Full-time, Part-time, Contract, Internship..."
    )
    seniority: Optional[str] = Field(
        default=None, description="Junior, Mid, Senior, Staff..."
    )
    salary_min: Optional[float] = None
    salary_max: Optional[float] = None
    salary_current: Optional[float] = None

    description: Optional[str] = None
    responsibilities: List[str] = Field(default_factory=list, sa_column=Column(JSON))
    requirements: List[str] = Field(default_factory=list, sa_column=Column(JSON))
    preferred_qualifications: List[str] = Field(default_factory=list, sa_column=Column(JSON))
    keywords: List[str] = Field(default_factory=list, sa_column=Column(JSON))
    missing_skills: List[str] = Field(default_factory=list, sa_column=Column(JSON))

    visa_sponsorship: bool = False
    application_deadline: Optional[datetime] = None
    apply_url: Optional[str] = None
    recruiter_email: Optional[str] = None
    summary: Optional[str] = Field(default=None, description="LLM-generated summary")
    score: Optional[float] = Field(
        default=None, description="Job match score generated by the Scoring Agent"
    )
    reasoning: Optional[str] = Field(
        default=None, description="Why the job received its score"
    )

    discovered_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    last_seen_at: datetime = Field(default_factory=datetime.utcnow)

    applied: bool = False
    archived: bool = False

    @field_validator("url", "apply_url")
    @classmethod
    def _validate_url_format(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return value
        AnyUrl(value)
        return value

