from pydantic import BaseModel, Field, HttpUrl
from datetime import datetime
from uuid import UUID, uuid4
from typing import Optional, List

class Job(BaseModel):
    id: UUID = Field(default_factory = uuid4)
    source: str = Field(...,
        description = "Where this job came from (firecrawl, greenhouse, lever, linkedin, etc.)" )
    url: HttpUrl
    company: str 
    title: str 
    location: Optional[str] = None
    country: Optional[str] = None 
    is_remote: bool = False
    remote_restrictions: Optional[str] = Field(
        default = None,
        description = "Remote only in US, Europe, etc."
    )
    employment_type: Optional[str] = Field(
        default = None,
        description = "Full-time, Part-time, Contract, Internship..."
    )
    seniority: Optional[str] = Field(
        default = None,
        description = "Junior, Mid, Senior, Staff..."
    )
    salary_min: Optional[float] = None
    salary_max: Optional[float] = None
    salary_current: Optional[float] = None
    description: Optional[str] = None 
    responsibilities: Optional[List[str]] = Field(default_factory = list)
    requirements: Optional[List[str]] = Field(default_factory = list)
    preferred_qualifications: Optional[List[str]] = Field(default_factory = list)
    visa_sponsorship: bool = False 
    application_deadline: Optional[datetime] = None 
    apply_url: Optional[HttpUrl] = None 
    recruiter_email: Optional[str] = None
    summary: Optional[str] = Field(
        default=None,
        description="LLM-generated summary"
    )

    keywords: List[str] = Field(default_factory=list)

    score: Optional[float] = Field(
        default=None,
        description="Job match score generated by the Scoring Agent"
    )

    reasoning: Optional[str] = Field(
        default=None,
        description="Why the job received its score"
    )

    missing_skills: List[str] = Field(default_factory=list)
    discovered_at: datetime = Field(default_factory=datetime.utcnow)

    updated_at: datetime = Field(default_factory=datetime.utcnow)

    applied: bool = False

    archived: bool = False

